import Link from 'next/link';
import { SiteShell, Meta, ConsultationBand } from './site-shell';
const solutions=[['01','AI & AGENT SYSTEMS','Autonomous and assisted agents for data processing, customer engagement, and internal operations.'],['02','AUTOMATION & WORKFLOWS','The invisible threads that connect software and eliminate manual repetition.'],['03','BUSINESS OPERATIONS','Systems shaped around the way your people actually work.'],['04','DATA & DASHBOARDS','Fragmented data made clear, actionable, and operational.']];
export default function Home(){return <SiteShell>
  <section className="hero container"><Meta left="ZION / CORPORATE SYSTEMS" right="EST. 2023"/><h1 className="display-xl">TOOLS FOR<br/><span>PEOPLE</span> AND<br/>MACHINES.</h1><div className="hero-bottom"><p className="lead">Zion Systems Corporation designs and builds digital systems that help people, organizations, and artificial intelligence work together.</p><div className="button-row"><Link className="button dark" href="/appointment/3">BOOK A STRATEGY CONSULTATION — $500</Link><Link className="text-link" href="/how-we-work">HOW IT WORKS ↗</Link></div></div></section>
  <section className="statement container section-rule"><Meta left="01 / POSITION" right="BUILD BETTER BUSINESS"/><div className="editorial-grid"><h2>LET’S BUILD<br/>WHAT COMES NEXT.</h2><p className="lead">Good technology should make an organization easier to operate. Zion builds the systems that make that possible—without unnecessary complexity or technology for technology’s sake.</p></div></section>
  <section className="container section-rule"><Meta left="02 / SOLUTIONS" right="SELECTED CAPABILITIES"/><div className="solution-list">{solutions.map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div><Link className="text-link block-link" href="/solutions">VIEW ALL SOLUTIONS ↗</Link></section>
  <section className="container section-rule"><Meta left="03 / HOW ZION WORKS" right="FROM PROBLEM TO PRODUCTION"/><div className="process-strip">{[['01','CONSULT'],['02','DECIDE'],['03','SCOPE'],['04','REVIEW'],['05','APPROVE'],['06','BUILD']].map(([n,t])=><div key={n}><b>{n}</b><strong>{t}</strong></div>)}</div></section>
  <section className="principles container section-rule"><Meta left="04 / OPERATING PRINCIPLES" right="TRUST IS INFRASTRUCTURE"/><div className="editorial-grid"><h2>CLEAR SCOPE.<br/>HUMAN GATES.<br/>USEFUL SYSTEMS.</h2><div><p className="lead">One accountable path from consultation through delivery.</p><ul><li>No unverified payment becomes fulfillment.</li><li>No tool intent becomes an automatic order.</li><li>No build begins without explicit approval.</li></ul></div></div></section><ConsultationBand/>
</SiteShell>}
