'use client';
import {FormEvent,useState} from 'react';
const interests=['AI / Agent Tool','Automation / Workflow Tool','CRM / Business Operations Tool','Data / Dashboard Tool','Integration / API Tool','Website / Customer Portal Tool','Internal Operations Tool','Not sure yet','Other'];
const times=['10:00 AM','11:00 AM','12:00 PM','1:00 PM','2:00 PM','3:00 PM'];
export function BookingFlow(){const[step,setStep]=useState(1);const[slot,setSlot]=useState('');const[ref,setRef]=useState('');function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setStep(3)}function confirm(){setRef(`ZSC-${Date.now().toString().slice(-8)}`);setStep(4)}return <section className="booking container"><div className="meta"><span>STRATEGY CONSULTATION / BOOKING</span><span>60 MIN / $500 USD / ONLINE</span></div><div className="booking-head"><h1>STRATEGY<br/>CONSULTATION.</h1><div><p className="price">$500 <small>ONE-TIME FEE / $0 TAX</small></p><p>A focused deep dive into your problem, operating environment, and technical feasibility. Consultation fees are non-refundable; Zion will reschedule at the earliest mutually available time.</p></div></div><ol className="stepper" aria-label="Booking progress"><li className={step>=1?'active':''}>01 / SCHEDULE</li><li className={step>=2?'active':''}>02 / INTAKE</li><li className={step>=3?'active':''}>03 / PAYMENT</li><li className={step>=4?'active':''}>04 / CONFIRM</li></ol>
{step===1&&<div className="flow-panel"><h2>SELECT A SESSION</h2><label>DATE<input type="date" min="2026-08-27" required/></label><label>TIMEZONE<select defaultValue="America/Chicago"><option>America/Chicago</option><option>America/New_York</option><option>America/Denver</option><option>America/Los_Angeles</option></select></label><fieldset><legend>AVAILABLE TIME</legend><div className="time-grid">{times.map(t=><button className={slot===t?'selected':''} key={t} type="button" onClick={()=>setSlot(t)}>{t}</button>)}</div></fieldset><button className="button dark" disabled={!slot} onClick={()=>setStep(2)}>CONTINUE TO INTAKE →</button></div>}
{step===2&&<form className="flow-panel form-grid" onSubmit={submit}><h2>YOUR DETAILS</h2><label>FULL NAME *<input name="name" autoComplete="name" required/></label><label>EMAIL *<input type="email" name="email" autoComplete="email" required/></label><label>PHONE NUMBER *<input type="tel" name="phone" autoComplete="tel" required/></label><fieldset><legend>STRATEGY SESSION PATH *</legend><label className="radio"><input type="radio" name="path" value="consultation" required/> Consultation only</label><label className="radio"><input type="radio" name="path" value="tool"/> Include tool order</label><p className="field-note">“Include tool order” records intent and $500 credit eligibility only. It does not authorize, price, or begin a build.</p></fieldset><label>I’M INTERESTED IN *<select required defaultValue=""><option value="" disabled>Select one</option>{interests.map(i=><option key={i}>{i}</option>)}</select></label><button className="button dark" type="submit">REVIEW PAYMENT →</button></form>}
{step===3&&<div className="flow-panel payment-review"><h2>PAYMENT HANDOFF</h2><dl><div><dt>STRATEGY CONSULTATION</dt><dd>$500.00</dd></div><div><dt>SALES TAX</dt><dd>$0.00</dd></div><div><dt>TOTAL USD</dt><dd>$500.00</dd></div></dl><p className="notice"><strong>PREVIEW SAFETY GATE.</strong> Production PayPal credentials and signed webhook validation are not present in the preservation package. This preview therefore cannot collect payment or mark an opportunity paid. Connect the authorized provider before acceptance testing.</p><button className="button dark" type="button" onClick={confirm}>SIMULATE APPROVED HANDOFF →</button><button className="text-button" type="button" onClick={()=>setStep(2)}>← RETURN TO INTAKE</button></div>}
{step===4&&<div className="flow-panel confirmation" role="status"><span className="confirm-mark">✓</span><h2>PREVIEW CONFIRMATION</h2><p>Reference <strong>{ref}</strong> demonstrates the confirmation presentation only. No payment, CRM opportunity, calendar event, or fulfillment record was created.</p><p>In production, confirmation is released only after a verified, idempotent $500 payment event and the required human approval gate.</p><button className="button dark" onClick={()=>{setStep(1);setSlot('');setRef('')}}>START OVER</button></div>}</section>}
